### PR TITLE
Funding payment & spending Log Update, GRINCC wallet corrections, Transparency Reports additions.

### PR DESCRIPTION
**Pull request by cekickafa**
[Funding request GK May-Aug 2023](https://forum.grin.mw/t/request-for-funding-cobragrin-may-aug-2023/10486/8) payment details.

### CODE REVIEW

**Review by Anynomouss — APPROVED** [review]

**Comment by cekickafa** [comment]
- Updated @cekickafa payment GK funding May-Aug 2023.
- Correction at Grincc.wallet, @stakervali Dec-Feb 2022 funding  payment should be same as @jankie  Dec-Feb 2022 as Gk.
-  Updated Btc spending logs.

**Review by Anynomouss — APPROVED** [review]

**Review by mojitoo — APPROVED** [review]

**Review by future3OOO — APPROVED** [review]

**Comment by Anynomouss** [comment]
@MCM-Mike, your approval for merging this would be appreciated, although technically we can already merge since we decided @cekickafa counts as  one reviewer.

**Review by Anynomouss — APPROVED** [review]

**Comment by Anynomouss** [comment]
Lets merge this ASAP. With new CC members we now should be able to get 4 approvals more easily.

**Review by trosel — APPROVED** [review]
We should go over how approvals work. Not sure what I'm looking at exactly. But from what I can discern, it looks fine to me

**Pull request merged**
