### PR TITLE
Include finacial resource table links + include DIR reports w/ Q3 & Q42021 reports + include spend_log.md 

### PR DESCRIPTION
**Pull request by newjack777**
PR includes an updated README.md with table linking to resources:
- addresses 
- transparency reports
- financial logs
- grin wallet

PR adds reports Directory with Q3 & Q4 transparency reports

PR adds spend_log.md financial log

### CODE REVIEW

**Comment by newjack777** [comment]
while calculating the spending_log.md file I used a 60 day SMA on day of send; calculated from https://coinmarketcap.com/historical/ - as the originating sender may be using a different method or different data, and with BTC value fluctuations these numbers are best used to serve as a transparent guide to spending and not an exact figure. 

Also as the community miners are beginning to launch I hope to include these inputs in future reports

**Comment by MCM-Mike** [comment]
added @davidtavarez @hendi @Anynomouss to also review this as this is required by https://github.com/grincc/docs/blob/main/approval-scheme.md

**Review by Anynomouss — APPROVED** [review]
Checked, nice and orderly overview

**Review by MCM-Mike — APPROVED** [review]
It looks good and organized. 

**Suggestion:** 
For the O1/2022 report please add a GRIN transaction CSV also to the repository.
@Anynomouss or @hendi can provide the TX log from our donation wallet.

**Comment by Anynomouss** [comment]
> It looks good and organized.
> 
> **Suggestion:** For the O1/2022 report please add a GRIN transaction CSV also to the repository. @Anynomouss or @hendi can provide the TX log from our donation wallet.

I updated the grincc-wallet.md, please verify @hendi

**Review by hendi — APPROVED** [review]

**Review by davidtavarez — APPROVED** [review]

**Pull request merged**
